dirs:
    train:
        data: /data/sxu/easton/data/AISHELL/train_phone_67.csv
        tfdata: /data/sxu/easton/data/AISHELL/tfdata/train
    dev:
        data: /data/sxu/easton/data/AISHELL/dev_phone_1k.csv
        tfdata: /data/sxu/easton/data/AISHELL/tfdata/dev_1k
    test:
        data: /data/sxu/easton/data/AISHELL/test_phone_67.csv
    vocab: /home/user/easton/projects/CipherGAN-tf2/data/vigenere345_brown200_vocab.txt

model:
    G:
        structure: fc
        num_hidden: 512
        num_layers: 1
        filter_count: 32
        filter_size: 1
    D:
        num_hidden: 512
        num_blocks: 5
        filter_count: 32
        filter_size: 1
        dropout: 0.5
    add_timing: concat
    dim_hidden: 512
    dropout: 0.5
    lp_distance: l1
    use_wasserstein: False
    use_embeddings: True
    original_l2: True
    loss_type: wgan  # loss_type

opti:
    type: adam
    D_G_rate: 5
    cycle_loss: 1.0
    wasserstein_loss: 10
    G:
        lr: 0.00005
    D:
        lr: 0.00002

dev_step: 50
decode_step: 50
save_step: 50

gpus: '0'
batch_size: 360
max_seq_len: 100
